### ISSUE TITLE
Allow different passwords for different purposes.

### ISSUE THREAD

**Issue by RezzedUp** [RezzedUp/OpGuard#7]
> **[Suggestion:](https://www.spigotmc.org/threads/opguard.147368/page-3#post-2055185)**
> And also, is it possible to set two different passwords for opguard op and deop. Because i'd like my Senior staff to be able to deop but not op.

**Comment by RezzedUp** [comment]
Proposed solution:
* Add multiple config options regarding which passwords to use for what.
```yaml
# By default, the same master password is used for all (since none are unique).

# If false, the master password will be used.
use-unique-op-password: false

# If false, the master password will be used.
use-unique-deop-password: false

# If false, the master password will be used.
use-unique-reload-password: false
```
* Update the **/opguard password** and **/opguard reset** commands to accommodate unique passwords.
```yaml
Without unique passwords:

  /og password <master password>

With unique passwords:

  /og password master <master password>
  /og password op <op password>
  /og password deop <deop password>
  /og password reload <reload password>
  (with corresponding /og reset options)
```
